### ISSUE TITLE
Not working if space is in key name?

### ISSUE THREAD

**Issue by goors** [Mercateo/serverless-image-processor#47]
If you have a space in key name (photo name), it will not work. You will just get 500 error code.

**Comment by goors** [comment]
In log you will have:

```
{ AccessDenied: Access Denied
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2019-12-04T18:31:20.011Z,
  requestId: '323BD788147273A6',
  extendedRequestId: 'kMUsrRjyhmFNVcp4uqIk8jdC+kUhZ54h0V0S2kSjgKWmw1sMLx/hkd5Cb0yTdevS4VUrrFNncr4=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 46.95926934397856 }
```

**Comment by goors** [comment]
if your photo name is `some photo.jpg` then key in `getObject` will be `some%20photo`. So the solution is to change your  `getObject` with:

```
 .getObject({
      Key: decodeURIComponent(key),
      Bucket: bucket
})
```

Of course, this only worked when I updated aws-sdk to latest (at this momment `2.584.0`)
